export const CHANGE_THEME = 'CHANGE_THEME';
export const CHANGE_COLOR = "CHANGE_COLOR";
export const CHANGE_SHADOW_BLUR = "CHANGE_SHADOW_BLUR";
export const CHANGE_BORDER_RADIUS = "CHANGE_BORDER_RADIUS";
export const CHANGE_SHADOW_LENGTH = "CHANGE_SHADOW_LENGTH";
export const CHANGE_DARK_SHADOW_FACTOR = "CHANGE_DARK_SHADOW_FACTOR";
export const CHANGE_LIGHT_SHADOW_FACTOR = "CHANGE_LIGHT_SHADOW_FACTOR";
export const INVERSE_FONT = "INVERSE_FONT";
export const THEME_RESET = "THEME_RESET";
export const CHANGE_BADGE_COLORS = "CHANGE_BADGE_COLORS";
export const CHANGE_STAGE = "CHANGE_STAGE";
export const CHANGE_SHOWCASE_COLOR = "CHANGE_SHOWCASE_COLOR";




